### ISSUE TITLE
Can't Save Player Options\clothing\presets after latest update 

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#35]
![Unbenannt](https://github.com/sneakyevil/SleepingDogs-ModMenu/assets/65475288/a50f97b5-243e-4ba2-9719-af5f6b96d83d)

Menue goes back to Player Options menue

**Comment by sneakyevil** [comment]
This has been already fixed in sponsored version few days ago.

**Comment by KabetzuriBoii** [comment]
even though this was closed ;D . it still doesnt work haha ;D
